programma_analisi_sperimentale: programma_analisi_sperimentale.c Makefile
	gcc -ansi -Wall -O programma_analisi_sperimentale.c -o Programma_analisi_sperimentale

pulisci:
	rm -f Programma_analisi_sperimentale
